server:
  servlet:
    context-path: /community

spring:
  datasource:
    url: jdbc:mysql://rm-uf69rj401r3kl7z42fo.mysql.rds.aliyuncs.com:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: community
    password: Hws246013
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  mail: #邮箱
    host: smtp.sina.com
    port: 465
    username: hanwensheng6013@sina.com
    password: 8f6ca826775c2d99
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    database: 0
    host: 121.5.178.21
    port: 6379
    password: 123456

  kafka:
    bootstrap-servers: 139.198.104.39:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

  data:
    elasticsearch:
      cluster-name: nowcoder
      cluster-nodes: 121.5.178.21:9300

  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

mybatis:
  type-aliases-package: com.nowcoder.community.entity #实体类别名
  mapper-locations: classpath:mapper/*.xml #制定mapper映射文件
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    use-generated-keys: true #自动生成id


#自用配置
community:
  path:
    domain: http://localhost:8080
    upload: /Users/wensheng/Documents/java/community/ziyuan #上传资源存放路径

#七牛
qiniu:
  key:
    access: eg_N8n_LHnqapcaqmNzMfFGcG13_fH4iyhA82gDO
    secret: O5x3RAHC_wW77mDHAjwEaXxV_9pb_7w7jq9MU8N9
  bucket:
    header:
      name: communityheader6013
      url: http://r8rlrfeww.hd-bkt.clouddn.com/

#caffeine
caffeine:
  posts:
    max-size: 15
    expire-second: 180
